# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:               Pocketsciencelab
tagline:             'Open Digital Research Environment Toolkit for the Advancement of Mathematics'
description:         'A project funded by the <a href="https://ec.europa.eu/programmes/horizon2020/">Horizon 2020</a> <a href="https://ec.europa.eu/programmes/horizon2020/en/h2020-section/european-research-infrastructures-including-e-infrastructures">European Research Infrastructures</a> Work Programme'
url:                 http://pocketsciencelab.eu
baseurl:             ''
paginate:            5
paginate_path:       "/news/page:num/"
gems:
  - jemoji

# About/contact
author:
  name:              'The OpenDreamKit consortium'
  url:               http://pocketsciencelab.eu
  email:             contact@pocketsciencelab.eu
  twitter:           opendreamkit

# Custom vars
version:             0.2.0
# Prose.io configuration
# Prose.io configuration
prose:
  editurl: "http://prose.io/#PocketScienceLab/PocketScienceLab.github.io/edit/master"
  siteurl: "http://pocketsciencelab.eu"
  ignore:
    - .gitignore
    - _config.yml
    - Gemfile
    - CNAME
    - LICENSE.md
    - atom.xml
    - index.md
    - 404.html
    - partners.html
    - news
    - public
    - _layouts
    - _includes
    - _data
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
